### ISSUE TITLE
After a quick glance a few suggestions

### ISSUE THREAD

**Issue by Maetco** [timothystone/roll20-character-sheets#1]
The charactersheet looks very nice. It does seem to have a problem in that it doesn't really have the necessary flexibility. For example the armour assumes that there are

Leather
Studded Leather
Mail
Plate

But what if I have Scale Mail or Gromril or Magic Armour?

The skills need to have a way to put a "custom" modifier. Talents, spells, equipment, statuses etc. can affect the skill roll.

The same idea is really needed everywhere. It's really nice to have a tight, graphically nice and quick to use sheet for all the normal rules but there needs to be a way to add custom modifiers to almost everything.

**Comment by timothystone** [comment]
@Maetco I want to distinguish core modifiers, i.e., test difficulty, skill mastery, versus _ad hoc_ in play modifiers. Making every roll button popup a modifier dialog feels wonky to me.

Right now, the character sheet mostly works. Do kick the tires. 

I do ask that concrete, objective, and actionable intent based bugs and core rules be submitted. The above is to subjective, "...same idea is really needed everywhere" is almost asking for a rewrite.

There is some possibility of extending the weapon modifiers "widget" currently in place as a skills and talents "widget."

I also like the idea of an editable armor section that can be used in `@{target}` calls by the GM. If you can write an actionable story for that, will consider it. I have some ideas though. Armor is duplicated right now and I don't like that much (sorta how I removed the duplication of Insanity Points).

I'm working on an API script that will do some of what you ask for weapons and skills. I have it working for basic combat rolls in DEV: to hit roll, location conversion, and sending a message to the chat.

``` text
====>
!kampf @{selected|token_id} attack WeaponSkill
<====
23 Hits! the Right Arm
```

It's very basic now, but I'm planing on extending that to even doing Ulric's Fury (with confirmation).

PS. Right now, I cannot act on house rules; I may consider them as part of a branch line of development. That branch can never be merged into the Master.

**Comment by Maetco** [comment]
" I want to distinguish core modifiers i.e., test difficulty, skill mastery,"

How do I add these (talents, test difficulties, etc.) to the rolls of the Sheet? I haven't found a way to do that except for Mastery and Grand Mastery.

**Comment by timothystone** [comment]
Talent modifiers are not currently supported. This is the goal of a skill/talent widget in the near future.

**Comment by Maetco** [comment]
That kind of was the point of my OP. At the moment we can't really use the sheet for rolling since it doesn't allow us to add the modifiers that occur in our games.

Just to make sure that there isn't a classic case of missunderstanding here, I'm not complaining. I tried the sheet and felt it was wonky and unfinished and started my comments from the obvious things that hit me in the face in the first seconds of testing it. I really appresiate you working on it and hope that you keep improving in the future as well. I'm not assuming that it'll become perfect and I'm not assuming that it'll get better tomorrow. I do realize that this is a hobby if even that to you.

**Comment by timothystone** [comment]
Can you explain the use of Mastery and Grand Mastery? _Skill_ Mastery is well understood, but Grand Mastery? That term does not appear in the book.

Skill Mastery is that process of taking Basic and Advanced Skills in three "levels." Basic Skills have an untrained "level" (1/2 Characteristic "level") and three (3) additional "mastery" levels: Taken, +10 and +20. These should be reflected on the sheet.

Advanced Skills must be Taken and advanced through +10 and +20. These Advanced Skills are not enumerated on the sheet, but must be Added individually. This makes sense to me as there is never an initial untrained state for Advanced Skills. You have it or you do not have it. Make sense?

The Advanced Skill section is not pretty right now, but it was working.

**Comment by timothystone** [comment]
No offense is taken. I'm learning the ropes of the R20 toolkit as well as supporting my favorite game.

**Comment by Maetco** [comment]
Never realized that Grand Mastery isn't an official term. Must have picked it up on some forums back when I started to use the system.

Mastery: +10
Grand Mastery: +20
