### ISSUE TITLE
Add Advanced Skills

### ISSUE THREAD

**Issue by Maetco** [timothystone/roll20-character-sheets#2]
The title.

**Comment by timothystone** [comment]
Advanced Skills are present, or should be, as a dynamic row, beneath the Basic Skills. You have to add each one. There are some formatting issues I'm working on. 

Please confirm you see this functionality?

**Comment by Maetco** [comment]
Yes it is there. It does seem logical that the skills aren't listed which the character doesn't have and the adding isn't a problem when you create one PC for yourself. But when you create 50 characters the additional work becomes a chore. This should also fix #3 for advanced skills.

**Comment by timothystone** [comment]
Closing. Advanced Skill are present. An enhancement is open to correct the formatting of all skills, basic and advanced.
