### ISSUE TITLE
SB, TB and added skills don't create attributes

### ISSUE THREAD

**Issue by Maetco** [timothystone/roll20-character-sheets#3]
This is problematic because now I can't link token abilities to them.

**Comment by timothystone** [comment]
Confirmed. The problem is in calculated attributes where the field is `disabled`. It is not sending the data to the backend to store on update.

**Comment by timothystone** [comment]
I will fix SB and TB. Please open new issues for "added skills" (not sure what that is actually, but I think you mean that Advance Skills don't create underlying attributes).

**Comment by timothystone** [comment]
Fixed in #12. Sorry @Maetco for such a long delay. I use this sheet in my campaign and I've been very lazy. Also fixed an hidden issue with wounds in #11.
