### ISSUE TITLE
Add Starting/Advance to Characteristics

### ISSUE THREAD

**Issue by tblackwe** [timothystone/roll20-character-sheets#4]
Can you make it look something like, at least in what data is available.

| Main | WS | BS | S | T | Ag | Int | WP | Fel |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Starting | 26 | 39 | 29 | 31 | 38 | 44 | 31 | 35 |
| Advance | 10 | 15 | 5 | 5 | 10 | 20 | 10 | 10 |
| Current | 26 | 44 | 29 | 31 | 48 | 54 | 36 | 45 |

| Secondary | A | W | SB | TB | M | Mag | IP | FP |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Starting | 1 | 12 | 2 | 3 | 4 | 0 | 0 | 3 |
| Advance |  |  | 1 |  |  |  |  |  |
| Current | 1 | 14 | 2 | 3 | 4 | 0 | 0 | 3 |

**Comment by timothystone** [comment]
I'm going to have to rework the sheet for this presentation, but it's definitely possible and actually needed to reflect character development.

I'm thinking something that may be closer to the current presentation that includes a series of "checkboxes" to reflect advances taken as well.

**Comment by timothystone** [comment]
Coming back to this almost a YEAR later. But I'm not sure I can do the advancement stuff (see restriction of Roll20 documentation below).

> **No Character Creation or Advancement**
> Due to copyright restrictions, please don't attempt to include functionality for advancing a character automatically to the next level or creating a new character from scratch automatically. It's fine to have attributes that auto-calculate based on other attributes (including the current level). We'll let you know if your submitted sheet violates this rule.

**Comment by tblackwe** [comment]
I was hoping for a reference point more than anything automated. So when I
am spending xp and I know career X gets a 20% boost to fellowship, how do I
know what my starting fellowship was? I have to go back and check all my
previous careers and remember if I've already gotten to 15%.

Or have I been leveling up characters wrong this whole time?

**Comment by timothystone** [comment]
Got it. I'm actually over a hurdle that prevented my from mastering github (time and practice). I'm redesigning the whole sheet.
